[project]
name = "pythonproject3"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "lww863712-cyber", email = "lwww863712@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
pythonproject3 = "pythonproject3:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
